# -*- coding: utf-8 -*-
"""
Translation Bridge for Cross-Lingual Event Matching

多言語イベントを英語に翻訳して意味的類似度を計算
Helsinki-NLP の無料翻訳モデルを使用

Author: Generated by GitHub Copilot
Date: 2025-11-20
"""

from transformers import MarianMTModel, MarianTokenizer
from langdetect import detect, DetectorFactory
import torch
from typing import List, Dict, Tuple
import numpy as np
import warnings

# 言語検出の再現性確保
DetectorFactory.seed = 42
warnings.filterwarnings('ignore')


class TranslationBridge:
    """多言語翻訳ブリッジ - イベント間の言語バリアを解消"""
    
    def __init__(self, cache_dir='./cache/translation', device=None):
        """
        Args:
            cache_dir (str): モデルキャッシュディレクトリ
            device (str): 'cuda' or 'cpu' (None=自動検出)
        """
        self.cache_dir = cache_dir
        self.device = device or ('cuda' if torch.cuda.is_available() else 'cpu')
        self.models = {}
        self.tokenizers = {}
        
        # サポート言語 (主要7言語)
        self.supported_langs = ['ja', 'es', 'fr', 'de', 'zh', 'ko', 'pt']
        
        # 翻訳モデルのロード
        self._load_translation_models()
    
    def _load_translation_models(self):
        """Helsinki-NLP翻訳モデルを事前ロード"""
        model_names = {
            'ja': 'Helsinki-NLP/opus-mt-ja-en',
            'es': 'Helsinki-NLP/opus-mt-es-en',
            'fr': 'Helsinki-NLP/opus-mt-fr-en',
            'de': 'Helsinki-NLP/opus-mt-de-en',
            'zh': 'Helsinki-NLP/opus-mt-zh-en',
            'ko': 'Helsinki-NLP/opus-mt-ko-en',
            'pt': 'Helsinki-NLP/opus-mt-tc-big-pt-en',  # Portuguese to English
        }
        
        print(f"\n[Translation Bridge] Loading translation models on {self.device}...")
        
        for lang, model_name in model_names.items():
            try:
                print(f"  Loading {lang} → en...", end=' ')
                
                # Tokenizer
                self.tokenizers[lang] = MarianTokenizer.from_pretrained(
                    model_name, 
                    cache_dir=self.cache_dir
                )
                
                # Model
                model = MarianMTModel.from_pretrained(
                    model_name, 
                    cache_dir=self.cache_dir
                )
                model = model.to(self.device)
                model.eval()  # Inference mode
                
                self.models[lang] = model
                
                print("✓")
                
            except Exception as e:
                print(f"✗ ({e})")
                # 失敗しても続行 (他の言語は使える)
        
        print(f"[Translation Bridge] Ready with {len(self.models)} language pairs")
    
    def detect_language(self, text: str) -> str:
        """
        言語を自動検出
        
        Args:
            text (str): 検出対象テキスト
        
        Returns:
            str: 言語コード (ja, es, en, etc.)
        """
        try:
            lang = detect(text)
            return lang if lang in self.supported_langs else 'en'
        except:
            # 検出失敗時は英語と仮定
            return 'en'
    
    def translate_to_english(
        self, 
        texts: List[str], 
        src_lang: str = None,
        batch_size: int = 32
    ) -> List[str]:
        """
        テキストを英語に翻訳
        
        Args:
            texts (List[str]): 翻訳するテキストのリスト
            src_lang (str): ソース言語 (None=自動検出)
            batch_size (int): バッチサイズ
        
        Returns:
            List[str]: 翻訳されたテキストのリスト
        """
        if not texts:
            return []
        
        # 言語検出 (最初のテキストで判断)
        if src_lang is None:
            src_lang = self.detect_language(texts[0])
        
        # 英語の場合はそのまま返す
        if src_lang == 'en':
            return texts
        
        # 未サポート言語
        if src_lang not in self.models:
            print(f"[Translation Warning] Unsupported language '{src_lang}', returning original texts")
            return texts
        
        # 翻訳実行
        model = self.models[src_lang]
        tokenizer = self.tokenizers[src_lang]
        
        translated = []
        
        # バッチ処理
        for i in range(0, len(texts), batch_size):
            batch = texts[i:i+batch_size]
            
            # トークン化
            try:
                inputs = tokenizer(
                    batch, 
                    return_tensors="pt", 
                    padding=True, 
                    truncation=True,
                    max_length=512
                )
                inputs = {k: v.to(self.device) for k, v in inputs.items()}
                
                # 翻訳生成
                with torch.no_grad():
                    outputs = model.generate(**inputs, max_length=512)
                
                # デコード
                batch_translated = tokenizer.batch_decode(outputs, skip_special_tokens=True)
                translated.extend(batch_translated)
                
            except Exception as e:
                print(f"[Translation Error] Batch {i//batch_size}: {e}")
                # エラー時は元のテキストを返す
                translated.extend(batch)
        
        return translated
    
    def translate_event(self, event: Dict) -> Dict:
        """
        イベント全体を翻訳 (コメント + トピック)
        
        Args:
            event (dict): {
                'comments': List[str],
                'topics': List[str],
                'language': str (optional)
            }
        
        Returns:
            dict: 翻訳されたイベント辞書
        """
        # 言語検出
        lang = event.get('language') or self.detect_language(event['comments'][0])
        
        # コメント翻訳
        translated_comments = self.translate_to_english(event['comments'], lang)
        
        # トピック翻訳
        translated_topics = self.translate_to_english(event['topics'], lang)
        
        return {
            'comments': translated_comments,
            'topics': translated_topics,
            'original_language': lang,
            'translated': lang != 'en'
        }
    
    def get_cross_lingual_similarity(
        self, 
        event_A: Dict, 
        event_B: Dict,
        bert_model
    ) -> Tuple[float, Dict]:
        """
        異なる言語のイベント間の類似度を計算
        
        Args:
            event_A (dict): イベントA
            event_B (dict): イベントB
            bert_model: SentenceTransformer モデル
        
        Returns:
            tuple: (類似度スコア, 詳細情報)
        """
        # 両方を英語に翻訳
        event_A_en = self.translate_event(event_A)
        event_B_en = self.translate_event(event_B)
        
        # BERT embedding計算
        emb_A = bert_model.encode(event_A_en['comments'], show_progress_bar=False)
        emb_B = bert_model.encode(event_B_en['comments'], show_progress_bar=False)
        
        # 平均ベクトル
        vec_A = np.mean(emb_A, axis=0)
        vec_B = np.mean(emb_B, axis=0)
        
        # Cosine similarity
        similarity = np.dot(vec_A, vec_B) / \
                     (np.linalg.norm(vec_A) * np.linalg.norm(vec_B))
        
        # 詳細情報
        details = {
            'lang_A': event_A_en['original_language'],
            'lang_B': event_B_en['original_language'],
            'translated_A': event_A_en['translated'],
            'translated_B': event_B_en['translated'],
            'cross_lingual': event_A_en['original_language'] != event_B_en['original_language']
        }
        
        return float(similarity), details
    
    def batch_translate_events(self, events: List[Dict]) -> List[Dict]:
        """
        複数イベントを一括翻訳
        
        Args:
            events (List[Dict]): イベントリスト
        
        Returns:
            List[Dict]: 翻訳済みイベントリスト
        """
        translated_events = []
        
        for i, event in enumerate(events):
            print(f"\r[Translation] Processing event {i+1}/{len(events)}", end='')
            translated_event = self.translate_event(event)
            translated_events.append(translated_event)
        
        print()  # 改行
        return translated_events
    
    def get_translation_stats(self, events: List[Dict]) -> Dict:
        """
        翻訳統計情報を取得
        
        Args:
            events (List[Dict]): イベントリスト
        
        Returns:
            dict: 統計情報
        """
        lang_counts = {}
        
        for event in events:
            lang = event.get('language') or self.detect_language(event['comments'][0])
            lang_counts[lang] = lang_counts.get(lang, 0) + 1
        
        return {
            'total_events': len(events),
            'language_distribution': lang_counts,
            'translation_required': sum(1 for e in events 
                                        if self.detect_language(e['comments'][0]) != 'en')
        }


# ==================== Testing Functions ====================

def test_basic_translation():
    """基本的な翻訳テスト"""
    print("\n" + "="*70)
    print("Translation Bridge - Basic Test")
    print("="*70)
    
    bridge = TranslationBridge()
    
    # テストケース
    test_cases = [
        ("久保すごい", "ja", "Kubo is amazing"),
        ("visca barca", "es", "long live barca"),
        ("allez les bleus", "fr", "go blues"),
        ("great goal", "en", "great goal"),
    ]
    
    print("\n[Translation Tests]")
    for text, lang, expected in test_cases:
        translated = bridge.translate_to_english([text], lang)
        print(f"  {lang}: '{text}' → '{translated[0]}'")
        print(f"      (Expected: '{expected}')")
    
    print("\n✓ Basic translation test complete")


def test_language_detection():
    """言語検出テスト"""
    print("\n" + "="*70)
    print("Translation Bridge - Language Detection Test")
    print("="*70)
    
    bridge = TranslationBridge()
    
    test_texts = [
        "This is English",
        "これは日本語です",
        "Esto es español",
        "C'est français",
        "Das ist Deutsch",
    ]
    
    print("\n[Language Detection]")
    for text in test_texts:
        detected = bridge.detect_language(text)
        print(f"  '{text}' → {detected}")
    
    print("\n✓ Language detection test complete")


if __name__ == '__main__':
    # Run tests
    test_language_detection()
    test_basic_translation()
    
    print("\n🎉 All tests passed!")
